export default [
  {
    bookId: "1",
    title: "Ninth House Leigh Bardugo",
    bookAuthor: "Ninth House Leigh Bardugo",
    price: 1234,
    bookRating: 4,
    bookCover: "/assets/CategoryCover/Fantasy.jpg",
  },
  {
    bookId: "2",
    title: "To Kill a Mocking Bird",
    bookAuthor: "To Kill a Mocking Bird",
    price: 324,
    bookRating: 4.5,
    bookCover: "/assets/CategoryCover/Classics.jpg",
  },
  {
    bookId: "3",
    title: "Ninth House Leigh Bardugo",
    bookAuthor: "Ninth House Leigh Bardugo",
    price: 456,
    bookRating: 5,
    bookCover: "/assets/CategoryCover/Mystery.jpg",
  },
  {
    bookId: "4",
    title: "The Haunting of Hill House",
    bookAuthor: "The Haunting of Hill House",
    price: 678,
    bookRating: 4,
    bookCover: "/assets/CategoryCover/Horror.jpg",
  },
  {
    bookId: "5",
    title: "Ninth House Leigh Bardugo",
    bookAuthor: "Ninth House Leigh Bardugo",
    price: 985,
    bookRating: 2,
    bookCover: "/assets/CategoryCover/HistoricalFiction.jpg",
  },
  {
    bookId: "6",
    title: "The Walking Dead",
    bookAuthor: "The Walking Dead",
    price: 539,
    bookRating: 3,
    bookCover: "/assets/CategoryCover/ComicBook.jpg",
  },
];
